### ISSUE TITLE
Validity checking for username/password

### ISSUE THREAD

**Issue by danielprofili** [KantwonsKids/DonationTracker#16]
Registration is allowed with an empty username and/or password.

**Comment by aschmitt8** [comment]
I think i've fixed it and now you can't register with an empty username or password. are there any other validation checks we need, like password of a certain length? also, would it be okay to push the changes to the registration-controller branch? will that automatically be included in the pull request for that branch or should i do something different? don't want to mess anything up

**Comment by ewilson72** [comment]
i put in a bunch of checks and committed them

**Comment by aschmitt8** [comment]
aw rats u beat me cause i didn't know where to commit

**Comment by ewilson72** [comment]
I forgot to accept the @ character in username.  I am a failure
